# Generated by Django 4.2.4 on 2023-08-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("nationality", models.CharField(max_length=50)),
                ("contact_number", models.CharField(max_length=15)),
                ("email_address", models.EmailField(max_length=254)),
                ("permanent_address", models.TextField()),
                ("current_address", models.TextField(blank=True, null=True)),
                ("guardian_full_name", models.CharField(max_length=100)),
                ("guardian_relationship", models.CharField(max_length=50)),
                ("guardian_contact_number", models.CharField(max_length=15)),
                ("guardian_email_address", models.EmailField(max_length=254)),
                ("emergency_contact_name", models.CharField(max_length=100)),
                ("emergency_contact_relationship", models.CharField(max_length=50)),
                ("emergency_contact_number", models.CharField(max_length=15)),
                ("previous_university", models.CharField(max_length=100)),
                ("previous_college", models.CharField(max_length=100)),
                ("register_number", models.CharField(max_length=20)),
                ("previous_course", models.CharField(max_length=100)),
                ("total_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("obt_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("year_of_study", models.PositiveIntegerField()),
                ("department", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("date", models.DateField()),
                (
                    "hostel_choice",
                    models.CharField(
                        choices=[("h1", "H1"), ("h2", "H2"), ("h3", "H3")],
                        max_length=20,
                    ),
                ),
                ("medical_conditions", models.TextField()),
                ("allergies", models.TextField()),
                ("id_copy", models.FileField(upload_to="id_copy/")),
                ("passport_photo", models.ImageField(upload_to="passport_photos/")),
                ("undertaking_form", models.FileField(upload_to="marks_card/")),
            ],
        ),
    ]
