# Generated by Django 4.2.4 on 2023-08-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="marks_card",
            field=models.FileField(default=0, upload_to="marks_card/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="undertaking_form",
            field=models.FileField(upload_to="undertaking_forms/"),
        ),
    ]
