# Generated by Django 4.2.4 on 2023-08-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0002_studentapplication_marks_card_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="studentapplication",
            table="hostelapp_studentapplication",
        ),
    ]
