# Generated by Django 4.2.4 on 2023-08-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0004_remove_studentapplication_marks_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="marks_card",
            field=models.FileField(default=0, upload_to="marks_card/"),
            preserve_default=False,
        ),
    ]
