# Generated by Django 4.2.4 on 2023-08-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0005_studentapplication_marks_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hostels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostelname",
                    models.CharField(max_length=30, verbose_name="hostelname"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[(1, "Male"), (2, "Female")], default=1, max_length=10
                    ),
                ),
                (
                    "lvevel",
                    models.CharField(
                        choices=[(1, "PG"), (2, "Phd")], default=1, max_length=30
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[(1, "MSc/MCA"), (2, "MA/Mcom/MPEd")],
                        default=1,
                        max_length=30,
                    ),
                ),
                ("no_rooms", models.IntegerField(default=0, verbose_name="no_rooms")),
                ("room_cap", models.IntegerField(default=0)),
                ("mess", models.BooleanField(default=False)),
                ("hostelfees", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
