# Generated by Django 4.2.4 on 2023-08-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0006_hostels"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hostels1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hostelname",
                    models.CharField(max_length=30, verbose_name="hostelname"),
                ),
                ("gender", models.CharField(max_length=10)),
                ("lvevel", models.CharField(max_length=30)),
                ("course", models.CharField(max_length=30)),
                ("no_rooms", models.IntegerField(default=0, verbose_name="no_rooms")),
                ("room_cap", models.IntegerField(default=0)),
                ("mess", models.BooleanField(default=False)),
                ("hostelfees", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
