# Generated by Django 4.2.4 on 2023-08-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0007_hostels1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hostels1",
        ),
        migrations.RemoveField(
            model_name="hostels",
            name="lvevel",
        ),
        migrations.AddField(
            model_name="hostels",
            name="level",
            field=models.CharField(
                choices=[("1", "PG"), ("2", "Phd")], default=1, max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="hostels",
            name="course",
            field=models.CharField(
                choices=[("1", "MSc/MCA"), ("2", "MA/Mcom/MPEd")],
                default=1,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="hostels",
            name="gender",
            field=models.CharField(
                choices=[("1", "Male"), ("2", "Female")], default=1, max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="hostels",
            name="hostelname",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="hostelname"
            ),
        ),
    ]
