# Generated by Django 4.2.4 on 2023-08-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hostelapp",
            "0008_delete_hostels1_remove_hostels_lvevel_hostels_level_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostels",
            name="hostelname",
            field=models.CharField(max_length=30, verbose_name="hostelname"),
        ),
    ]
