# Generated by Django 4.2.4 on 2023-08-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0009_alter_hostels_hostelname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostels",
            name="hostelname",
            field=models.CharField(max_length=20, verbose_name="hostelname"),
        ),
    ]
