# Generated by Django 4.2.4 on 2023-08-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0011_alter_hostels_hostelname"),
    ]

    operations = [
        migrations.CreateModel(
            name="add_dep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dep_name", models.CharField(max_length=100)),
                ("dep_contact", models.CharField(max_length=15)),
                ("dep_email", models.EmailField(max_length=254)),
            ],
        ),
    ]
