# Generated by Django 4.2.4 on 2023-09-03 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0014_alter_studentapplication_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentapplication",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="emergency_contact_number",
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="emergency_contact_relationship",
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="guardian_email_address",
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="cast",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="cast_no",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="course",
            field=models.CharField(
                choices=[("1", "MSc/MCA"), ("2", "MA/Mcom/MPEd")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hostelapp.add_dep"
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="gender",
            field=models.CharField(
                choices=[("1", "Male"), ("2", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="hostel_choice",
            field=models.ForeignKey(
                limit_choices_to={
                    "course": models.F("course"),
                    "gender": models.F("gender"),
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_applications",
                to="hostelapp.hostels",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
