# Generated by Django 4.2.4 on 2023-09-03 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0015_remove_studentapplication_emergency_contact_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="hostel_choice",
            field=models.ForeignKey(
                limit_choices_to={
                    "course": models.F("course"),
                    "gender": models.F("gender"),
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="StudentApplication",
                to="hostelapp.hostels",
            ),
        ),
    ]
