# Generated by Django 4.2.4 on 2023-09-03 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0016_alter_studentapplication_hostel_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="hostel_choice",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hostelapp.hostels",
            ),
        ),
    ]
