# Generated by Django 4.2.4 on 2023-09-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0019_gender_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gender_type",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="hostels",
            name="course",
            field=models.CharField(
                choices=[("MSc/MCA", "MSc/MCA"), ("MA/Mcom/MPEd", "MA/Mcom/MPEd")],
                default=1,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="hostels",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default=1,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="hostels",
            name="level",
            field=models.CharField(
                choices=[("PG", "PG"), ("Phd", "Phd")], default=1, max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="course",
            field=models.CharField(
                choices=[("MSc/MCA", "MSc/MCA"), ("MA/Mcom/MPEd", "MA/Mcom/MPEd")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
    ]
