# Generated by Django 4.2.4 on 2023-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0020_alter_gender_type_gender_alter_hostels_course_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="course_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("MSc/MCA", "MSc/MCA"),
                            ("MA/Mcom/MPEd", "MA/Mcom/MPEd"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
