# Generated by Django 4.2.4 on 2023-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0022_remove_warden_dep_name_remove_warden_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
