# Generated by Django 4.2.4 on 2023-09-15 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0023_studentapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="room_allotted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="RoomAllotment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=10)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostelapp.hostels",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostelapp.studentapplication",
                    ),
                ),
            ],
        ),
    ]
