# Generated by Django 4.2.4 on 2023-09-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0024_studentapplication_room_allotted_roomallotment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomallotment",
            name="room_number",
            field=models.IntegerField(max_length=10),
        ),
    ]
