# Generated by Django 4.2.4 on 2023-09-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0025_alter_roomallotment_room_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomallotment",
            name="room_number",
            field=models.IntegerField(),
        ),
    ]
