# Generated by Django 4.2.4 on 2023-09-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0026_alter_roomallotment_room_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="fee_status",
            field=models.IntegerField(default=0),
        ),
    ]
