# Generated by Django 4.2.4 on 2023-09-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0027_studentapplication_fee_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=16)),
                ("expiry_date", models.CharField(max_length=5)),
                ("cvv", models.CharField(max_length=4)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "student_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostelapp.studentapplication",
                    ),
                ),
            ],
        ),
    ]
