# Generated by Django 4.2.4 on 2023-09-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0035_studentapplication_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentapplication",
            name="user_id",
        ),
    ]
