# Generated by Django 4.2.4 on 2023-09-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0036_remove_studentapplication_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="allergies",
            field=models.TextField(verbose_name="Allergies"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="cast",
            field=models.CharField(max_length=10, verbose_name="Cast"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="cast_no",
            field=models.CharField(max_length=15, verbose_name="Cast No"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="contact_number",
            field=models.CharField(max_length=15, verbose_name="Contact Number"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="course",
            field=models.CharField(
                choices=[("MSc/MCA", "MSc/MCA"), ("MA/Mcom/MPEd", "MA/Mcom/MPEd")],
                max_length=100,
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="current_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Current Address"
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="date_of_birth",
            field=models.DateField(verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hostelapp.add_dep",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="email_address",
            field=models.EmailField(max_length=254, verbose_name="Email Address"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="fee_status",
            field=models.IntegerField(default=0, verbose_name="Fee Status"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="guardian_contact_number",
            field=models.CharField(
                max_length=15, verbose_name="Guardian Contact Number"
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="guardian_full_name",
            field=models.CharField(max_length=100, verbose_name="Guardian Full Name"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="guardian_relationship",
            field=models.CharField(max_length=50, verbose_name="Guardian Relationship"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="hostel_choice",
            field=models.ForeignKey(
                limit_choices_to={
                    "course": models.F("course"),
                    "gender": models.F("gender"),
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_applications",
                to="hostelapp.hostels",
                verbose_name="Hostel Choice",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="id_copy",
            field=models.FileField(upload_to="id_copy/", verbose_name="ID Copy"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="marks_card",
            field=models.FileField(upload_to="marks_card/", verbose_name="Marks Card"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="medical_conditions",
            field=models.TextField(verbose_name="Medical Conditions"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="nationality",
            field=models.CharField(max_length=50, verbose_name="Nationality"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="obt_marks",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Obtained Marks"
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="passport_photo",
            field=models.ImageField(
                upload_to="passport_photos/", verbose_name="Passport Photo"
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Percentage",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="permanent_address",
            field=models.TextField(verbose_name="Permanent Address"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="previous_college",
            field=models.CharField(max_length=100, verbose_name="Previous College"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="previous_course",
            field=models.CharField(max_length=100, verbose_name="Previous Course"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="previous_university",
            field=models.CharField(max_length=100, verbose_name="Previous University"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="register_number",
            field=models.CharField(max_length=20, verbose_name="Register Number"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="room_allotted",
            field=models.BooleanField(default=False, verbose_name="Room Allotted"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="status",
            field=models.IntegerField(default=0, verbose_name="Status"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="total_marks",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Total Marks"
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="undertaking_form",
            field=models.FileField(
                upload_to="undertaking_forms/", verbose_name="Undertaking Form"
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="year",
            field=models.PositiveIntegerField(verbose_name="Year"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="year_of_study",
            field=models.PositiveIntegerField(verbose_name="Year of Study"),
        ),
    ]
