# Generated by Django 4.2.4 on 2023-09-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0037_alter_studentapplication_allergies_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warden",
            name="dep_id",
        ),
        migrations.DeleteModel(
            name="RoomStudentMapping",
        ),
    ]
