# Generated by Django 4.2.4 on 2023-09-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0039_alter_studentapplication_hostel_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("room_number", models.IntegerField()),
                ("complaint_text", models.TextField()),
            ],
        ),
    ]
