# Generated by Django 4.2.4 on 2023-09-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0041_studentapplication_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentapplication",
            name="user",
        ),
    ]
