# Generated by Django 4.2.4 on 2023-09-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0042_remove_studentapplication_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="course",
            field=models.CharField(
                choices=[("Course1", "Course 1"), ("Course2", "Course 2")],
                max_length=100,
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="fee_status",
            field=models.IntegerField(
                choices=[(0, "Not Paid"), (1, "Paid")],
                default=0,
                verbose_name="Fee Status",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Pending"), (1, "Approved"), (2, "Rejected")],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
