# Generated by Django 4.2.4 on 2023-10-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0043_alter_studentapplication_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="complaint_status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AddField(
            model_name="complaint",
            name="hostel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="hostelapp.hostels",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="complaint",
            name="room_number",
            field=models.CharField(max_length=10),
        ),
    ]
