# Generated by Django 4.2.4 on 2023-10-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0045_messbill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messbill",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="messbill",
            name="uploaded_bill",
        ),
        migrations.AddField(
            model_name="messbill",
            name="mess_bill_image",
            field=models.ImageField(blank=True, null=True, upload_to="mess_bills/"),
        ),
    ]
