# Generated by Django 4.2.4 on 2023-10-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0047_remove_messbill_student_messbill_room_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="complaint_status",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="hostel",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="room_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="messbill",
            name="room_number",
            field=models.IntegerField(),
        ),
    ]
