# Generated by Django 4.2.4 on 2023-10-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0049_complaint_hostel"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="complaint_status",
            field=models.IntegerField(
                choices=[(0, "Pending"), (1, "Approved"), (2, "Rejected")],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
