# Generated by Django 4.2.4 on 2023-10-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0050_complaint_complaint_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="hostel",
        ),
    ]
