# Generated by Django 4.2.4 on 2023-10-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0051_remove_complaint_hostel"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="hostel",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
