# Generated by Django 4.2.4 on 2023-10-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0052_complaint_hostel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="course",
            field=models.CharField(
                choices=[("MSc/MCA", "MSc/MCA "), ("MA", "MA")],
                max_length=100,
                verbose_name="Course",
            ),
        ),
    ]
