# Generated by Django 4.2.4 on 2023-10-05 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hostelapp", "0053_alter_studentapplication_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDetailStudents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("challen_number", models.CharField(max_length=20)),
                ("challen_image", models.ImageField(upload_to="challen_images/")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostelapp.studentapplication",
                    ),
                ),
            ],
        ),
    ]
